version: '1.3'


services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sumit
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

    ports:
      - "3306:3306"
    volumes:
      - newvol:/var/lib/mysql
    networks:
      - newnetwork

  backend:
    build: sumit1968/backend:latest
    container_name: backend
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=sumit
      - DB_PORT=3306
      - CLIENT_ORIGIN=http://localhost:8081
    networks:
      - newnetwork
  
  frontend:
    build: sumit1968/frontend:latest
    container_name: frontend
    ports:
      - "8081:8081"
    networks:
      - newnetwork
    
volumes:
  newvol:

networks:
  newnetwork:






















